### ISSUE TITLE
4.1.9 tencent_im_sdk_plugin 会导致 iOS 打包丢失 version

### ISSUE THREAD

**Issue by hellohejinyu** [TencentCloud/TIMSDK#1262]
【iOS Flutter】
【集成包】：tencent_im_sdk_plugin
【当前现象】：打包 iOS 报错，Android 正常，报错内容看下面的我给 Flutter 提的 issue，里面很详细的。
【机型】：iOS
【之前版本有无此问题】：4.1.8 之前正常，4.1.8、4.1.9 均有此问题
【有无日志或者截图】：看下面的我给 Flutter 提的 issue，里面很详细的。

**Comment by hellohejinyu** [comment]
https://github.com/flutter/flutter/issues/113907#issue-1419698652

我在 QQ 上问过你们的开发，回复我说他那边没复现这个问题。所以我给 Flutter 提了个 issue。但是 Flutter 官方还是觉得是第三方插件问题。不过我自己试了，4.1.3 版本是正常的。我对比了 4.1.3 和 4.1.9 的代码，没发现啥可疑的东西。所以就很困惑。

**Comment by Android-chenqihang** [comment]
我也遇见了这个问题

**SDK版本：  tim_ui_kit: ^0.1.8**

**Flutter版本：**
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.5, on macOS 12.6 21G115 darwin-arm, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.2)
[✓] VS Code (version 1.72.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

**报错日志**
Launching lib/main.dart on iPhone 14 in debug mode...
Running Xcode build...
Xcode build done.                                           16.7s
Unable to install /xxxx/xxxxx/myapp/build/ios/iphonesimulator/Runner.app on F46157A1-3A87-411D-9143-13F4AD1D8459. This is sometimes caused by a malformed plist file:
ProcessException: Process exited abnormally:
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The application's Info.plist does not contain a valid CFBundleShortVersionString.
Ensure your bundle contains a valid CFBundleShortVersionString.
  Command: /usr/bin/arch -arm64e xcrun simctl install F46157A1-3A87-411D-9143-13F4AD1D8459 /Users/xxxx/myapp/build/ios/iphonesimulator/Runner.app
Error launching application on iPhone 14.

**Comment by DavidMGT** [comment]
我们也遇到了。。赶紧解决 啊

**Comment by RoleWong** [comment]
> 

您好，建议您先手动将build version写入Xcode中，非常感谢。如图所示：
<img width="1643" alt="image" src="https://user-images.githubusercontent.com/24520036/199162505-a535c89f-95c0-45bd-9de4-e99a7d47a2cf.png">

这个问题，我们会尽快优化解决。

**Comment by RoleWong** [comment]
> 我也遇见了这个问题
> 
> **SDK版本： tim_ui_kit: ^0.1.8**
> 
> **Flutter版本：** flutter doctor Doctor summary (to see all details, run flutter doctor -v): [✓] Flutter (Channel stable, 3.3.5, on macOS 12.6 21G115 darwin-arm, locale zh-Hans-CN) [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0) [✓] Xcode - develop for iOS and macOS (Xcode 14.0.1) [✓] Chrome - develop for the web [✓] Android Studio (version 2021.2) [✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3) [✓] IntelliJ IDEA Ultimate Edition (version 2022.2.2) [✓] VS Code (version 1.72.2) [✓] Connected device (2 available) [✓] HTTP Host Availability
> 
> **报错日志** Launching lib/main.dart on iPhone 14 in debug mode... Running Xcode build... Xcode build done. 16.7s Unable to install /xxxx/xxxxx/myapp/build/ios/iphonesimulator/Runner.app on F46157A1-3A87-411D-9143-13F4AD1D8459. This is sometimes caused by a malformed plist file: ProcessException: Process exited abnormally: An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22): Failed to install the requested application The application's Info.plist does not contain a valid CFBundleShortVersionString. Ensure your bundle contains a valid CFBundleShortVersionString. Command: /usr/bin/arch -arm64e xcrun simctl install F46157A1-3A87-411D-9143-13F4AD1D8459 /Users/xxxx/myapp/build/ios/iphonesimulator/Runner.app Error launching application on iPhone 14.

**Comment by hexingcheng** [comment]
您好，建议您先手动将build version写入Xcode中，非常感谢。如图所示：
image

这个问题，目前已内部定位并解决。预计将于十一月发布中旬的版本发布修复。
